name: contact_list_view
description: "A new Flutter project."
version: 1.0.0
homepage: https://github.com/Matkurban
repository: https://github.com/Matkurban/contact_list_view
topics:
  - widget
  - azlistview
  - contact
  - chat
screenshots:
  - description: 'contact list'
    path: doc/images/Screenshot_20260202_224751.jpg
  - description: 'contact list'
    path: doc/images/Screenshot_20260202_222935.jpg


environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.3.0
  scrollview_observer: ^1.26.3
  flutter_sticky_header: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

